#!/bin/bash

# UBUNTU server security hardening checklist script.
# Checks for most common security issues.

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[0;33m'

source ./helpers
source ./ssh
source ./ports

check_ssh
check_open_ports
